import { InboundTransaction } from '../types';
import { formatDate } from './formatters';

export function exportTransactionsToCsv(transactions: InboundTransaction[], filename = 'IR_Transactions_Report') {
  const headers = [
    'No',
    'Transaction Ref',
    'UETR Ref',
    'Sender Name',
    'Sender Country',
    'Sending Bank',
    'BIC',
    'Currency',
    'Amount',
    'Exchange Rate (MMK)',
    'Converted Amount (MMK)',
    'Fee (MMK)',
    'Net Amount (MMK)',
    'Beneficiary Account',
    'Value Date',
    'Status',
    'Remittance Info'
  ];

  const rows = transactions.map((tx, idx) => [
    idx + 1,
    `"${tx.transactionRef}"`,
    `"${tx.swiftMetadata.uetr}"`,
    `"${tx.senderName.replace(/"/g, '""')}"`,
    `"${tx.senderCountry}"`,
    `"${tx.sendingBank.replace(/"/g, '""')}"`,
    `"${tx.sendingBankBic}"`,
    `"${tx.currency}"`,
    tx.amount,
    tx.exchangeRate,
    tx.convertedAmountMmk,
    tx.feeAmount,
    tx.netAmountMmk,
    `"${tx.beneficiaryAccount}"`,
    `"${formatDate(tx.valueDate)}"`,
    `"${tx.status}"`,
    `"${tx.swiftMetadata.remittanceInfo.replace(/"/g, '""')}"`
  ]);

  const csvContent = [headers.join(','), ...rows.map(e => e.join(','))].join('\r\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}_${new Date().toISOString().slice(0, 10)}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportSingleTransactionAdvice(tx: InboundTransaction) {
  const content = `
================================================================================
                    KBZ BANK - INBOUND REMITTANCE ADVICE
                         SWIFT MT103 / GPI CONFIRMATION
================================================================================
Date of Issue    : ${formatDate(new Date().toISOString())}
Transaction Ref  : ${tx.transactionRef}
UETR Tracking ID : ${tx.swiftMetadata.uetr}
Status           : ${tx.status.toUpperCase()}
--------------------------------------------------------------------------------
SENDER / ORDERING CUSTOMER:
  Name           : ${tx.senderName}
  Country        : ${tx.senderCountry}
  Ordering Bank  : ${tx.sendingBank} (BIC: ${tx.sendingBankBic})

BENEFICIARY DETAILS:
  Account Name   : ${tx.swiftMetadata.beneficiaryCustomer.name}
  Account Number : ${tx.beneficiaryAccount}
  Beneficiary Bank: KBZ Bank Ltd (BIC: ${tx.swiftMetadata.accountWithInstitution.bic})
  Branch         : ${tx.swiftMetadata.accountWithInstitution.branch}

TRANSACTION & FX PARTICULARS:
  Original Currency & Amount : ${tx.currency} ${tx.amount.toLocaleString('en-US', { minimumFractionDigits: 2 })}
  Exchange Rate Applied      : 1 ${tx.currency} = ${tx.exchangeRate.toLocaleString()} MMK
  Gross Converted (MMK)      : ${tx.convertedAmountMmk.toLocaleString()} MMK
  Handling / Interbank Fee   : ${tx.feeAmount.toLocaleString()} MMK
  Net Credited Amount (MMK)  : ${tx.netAmountMmk.toLocaleString()} MMK
  Value Date & Time          : ${formatDate(tx.valueDate)}
  Charge Details             : ${tx.swiftMetadata.detailsOfCharges}
  Payment Purpose / Ref      : ${tx.swiftMetadata.remittanceInfo}
--------------------------------------------------------------------------------
SETTLEMENT AUDIT TRAIL:
${tx.swiftMetadata.settlementSteps.map(s => `  [${s.completed ? 'COMPLETED' : s.failed ? 'FAILED' : 'PENDING'}] ${s.timestamp}: ${s.title} - ${s.description}`).join('\n')}
================================================================================
This advice is electronically generated by KBZ Inbound Remittance System.
For verification or queries, please contact corporate.fx@kbzbank.com
================================================================================
`;

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `SWIFT_Advice_${tx.transactionRef}.txt`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
